### ISSUE TITLE
 FastAPI Response Model not working 

### ISSUE THREAD

**Issue by dtreglia06** [acwazz/fastapi-responseschema#1]
Using the library both the response_model and the response_model_exclude filters have stopped working. 
How can i resolve it?

**Comment by acwazz** [comment]
Added tests reproducing the issue, Fixed `response_model_exclude` filter problem in c905a616439e7a68dbbc586214c837e8115ef3d6 .

**Comment by acwazz** [comment]
The issue was about a documentation error and a fastapi version prior to `0.66.0`.  
https://github.com/tiangolo/fastapi/issues/3335
Updated dependency for fastapi to `>= 0.66.0`. Updated docs explaining how to handle this case.
