### ISSUE TITLE
[BUG] - cannot import name 'DictIntStrAny' from 'fastapi.encoders

### ISSUE THREAD

**Issue by lifengmds** [acwazz/fastapi-responseschema#98]
**Environment**
- `fastapi` version is: 0.104.1
- `fastapi-responseschema` version is:  branch dependabot/pip/master/fastapi-0.104.1
- `python` version is: 3.9

**Describe the bug**
    from .interfaces import AbstractResponseSchema
  File ".venv/lib/python3.9/site-packages/fastapi_responseschema/interfaces.py", line 8, in <module>
    from fastapi.encoders import DictIntStrAny, SetIntStr
ImportError: cannot import name 'DictIntStrAny' from 'fastapi.encoders' (.venv/lib/python3.9/site-packages/fastapi/encoders.py)

**Comment by acwazz** [comment]
Hello, first of all thanks for reporting this issue. I am working on extending support for `fastapi>=0.100.0` and `python==3.12`. 
I plan to release it as soon as possible (hopefully this week).

I will keep you updated on this ticket.

**Comment by acwazz** [comment]
Well, looks like it wasn't a long task, here you go: https://github.com/acwazz/fastapi-responseschema/releases/tag/2.1.0

I will close this issue, feel free to reopen if you experience any problem.
